# Copyright (C) 2011-2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/nicki/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/nicki/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/sony/nicki/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/sony/nicki/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/nicki/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/sony/nicki/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/sony/nicki/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/nicki/proprietary/bin/ks:system/bin/ks \
    vendor/sony/nicki/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sony/nicki/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/nicki/proprietary/bin/qcks:system/bin/qcks \
    vendor/sony/nicki/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/nicki/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sony/nicki/proprietary/bin/ta_reader:system/bin/ta_reader \
    vendor/sony/nicki/proprietary/bin/ta_qmi_service:system/bin/ta_qmi_service \
    vendor/sony/nicki/proprietary/bin/taimport:system/bin/taimport \
    vendor/sony/nicki/proprietary/bin/thermald:system/bin/thermald \
    vendor/sony/nicki/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/nicki/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/sony/nicki/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/sony/nicki/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/sony/nicki/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/sony/nicki/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/sony/nicki/proprietary/etc/thermald-8064.conf:system/etc/thermald-8064.conf \
    vendor/sony/nicki/proprietary/etc/thermald-8930.conf:system/etc/thermald-8930.conf \
    vendor/sony/nicki/proprietary/etc/thermald-8960.conf:system/etc/thermald-8960.conf \
    vendor/sony/nicki/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/sony/nicki/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/sony/nicki/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/sony/nicki/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/sony/nicki/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/sony/nicki/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/nicki/proprietary/etc/firmware/dxhdcp2.flist:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/nicki/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/sony/nicki/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.flist:system/etc/firmware/tzlibasb.flist \
    vendor/sony/nicki/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.flist:system/etc/firmware/tzsuntory.flist \
    vendor/sony/nicki/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/nicki/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/sony/nicki/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/sony/nicki/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/sony/nicki/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/sony/nicki/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/sony/nicki/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/sony/nicki/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/sony/nicki/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/sony/nicki/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/sony/nicki/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/sony/nicki/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/sony/nicki/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/sony/nicki/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/sony/nicki/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/sony/nicki/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/sony/nicki/proprietary/lib/hw/audio.primary.msm8960.so:system/lib/hw/audio.primary.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/audio_policy.msm8960.so:system/lib/hw/audio_policy.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/copybit.msm8960.so:system/lib/hw/copybit.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/gralloc.msm8960.so:system/lib/hw/gralloc.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/hwcomposer.msm8960.so:system/lib/hw/hwcomposer.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/sony/nicki/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/sony/nicki/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.msm8960.so \
    vendor/sony/nicki/proprietary/lib/hw/sensors.qcom.so:system/lib/hw/sensors.qcom.so \
    vendor/sony/nicki/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/sony/nicki/proprietary/lib/lib_get_secure_mode.so:system/lib/lib_get_secure_mode.so \
    vendor/sony/nicki/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/sony/nicki/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/nicki/proprietary/lib/libcredential-manager-service.so:system/lib/libcredential-manager-service.so \
    vendor/sony/nicki/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/sony/nicki/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/sony/nicki/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/sony/nicki/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/sony/nicki/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/sony/nicki/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/sony/nicki/proprietary/lib/libface.so:system/lib/libface.so \
    vendor/sony/nicki/proprietary/lib/libfmradio.so:system/lib/libfmradio.so \
    vendor/sony/nicki/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/sony/nicki/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/sony/nicki/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/sony/nicki/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/sony/nicki/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/nicki/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/sony/nicki/proprietary/lib/libkeyctrl.so:system/lib/libkeyctrl.so \
    vendor/sony/nicki/proprietary/lib/liblights-core.so:system/lib/liblights-core.so \
    vendor/sony/nicki/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/sony/nicki/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/sony/nicki/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/sony/nicki/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/sony/nicki/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/nicki/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/sony/nicki/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/sony/nicki/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/sony/nicki/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/nicki/proprietary/lib/libpin-cache.so:system/lib/libpin-cache.so \
    vendor/sony/nicki/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/sony/nicki/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/sony/nicki/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/sony/nicki/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/sony/nicki/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/sony/nicki/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/sony/nicki/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/sony/nicki/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/sony/nicki/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/sony/nicki/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/sony/nicki/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/sony/nicki/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/sony/nicki/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/sony/nicki/proprietary/lib/libta.so:system/lib/libta.so \
    vendor/sony/nicki/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so
